server:
  port: 8761  # 指定该Eureka实例的端口
eureka:
  instance:
    preferIpAddress: true
    hostname: discovery1.99bill.com # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
spring:
  application:
    name: hippo-eureka