server:
  port: 8761
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://user:password123@localhost:${server.port}/eureka
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
spring:
  application:
    name: hippo-eureka