spring:
  application:
    name: hippo-spring-boot-v1
server:
  port: 18089
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery1.99bill.com:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true


