server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/changealice/hippo-config
          searchPaths: dev
  application:
    name: hippo-config-server