server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/changealice/hippo-config
#          uri: file://${user.home}/hippo-config
  application:
    name: hippo-config-server