spring:
  application:
    name: hippo-spring-boot-consumer-ribbon
server:
  port: 18083
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery1.99bill.com:8761/eureka/
  instance:
    preferIpAddress: true